config/routes.rb
Rails.application.routes.draw do
  resources :recipient_lists
  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  devise_for :users
  root to: "home#index"

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations'
  # }

  # resource :users, only: [:edit] do
  #   resource :profile, except: [:index], controller: 'users/profile' do
  #     member do
  #       put :update
  #     end
  #   end
  #   collection do
  #     put 'update_password'
  #   end
  # end
  resources :campaigns
  resources :emails

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_paper_trail
  belongs_to :user
  has_many :emails

  validates :completion_status, inclusion: { in: ["Testing", "QA"] }, allow_nil: true

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def index
    @campaigns = Campaign.order('created_at DESC')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campaigns }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @campaign }
    end
  end

  def new
    @campaign = current_user.campaigns.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @campaign }
    end
  end

  def edit
  end

  def create
    # gimmie = params[:campaign].merge params.except("campaign", "action", "controller", "url")
    @campaign = current_user.campaigns.new(campaign_params)
    respond_to do |format|
      if @campaign.save
        format.html { redirect_to campaigns_url, status: 301, #redirect_to @user, status: 301,
         notice: 'Campaign was successfully created.' }
        format.json { render json: @campaign, status: :created, location: @campaign }
      else
        format.html { render action: "new" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @campaign.update_attributes(campaign_params)
        format.html { redirect_to :back, status: 301, notice: 'Campaign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url }
      format.json { head :no_content }
    end
  end

  private
  def set_campaign
    @campaign = Campaign.find(params[:id])
  end

  def campaign_params
    params.require(:campaign).permit(:id, :user, :completion_status, :name, :client_name)
  end
end

app/views/campaigns/_form.html.erb
<%= simple_form_for(@campaign) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :name, label: "Campaign Name" %>
    <%= f.input :client_name, label: "Client Name" %>
    <%= f.input :completion_status, collection: ["Testing", "QA"], include_blank: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<div class="container">
  <div class="row">
    <div class="panel col-md-12 col-md-12">
      <h1 class="lead">Editing Campaign: <span><%= @campaign.name %></span></h1>
      <%= render 'form' %>
      <%= link_to 'Back', campaigns_path %>
    </div>
  </div>

</div>

app/views/campaigns/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-md-12">
      <h1 class="lead">Listing Camapigns</h1>
      <p><%= link_to 'New Campaign', new_campaign_path, class: "button" %></p>

      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>Client Name</th>
              <th>Campaign Name</th>
              <th>Status</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @campaigns.each do |campaign| %>
              <tr>
                <td><%= campaign.client_name %></td>
                <td><%= campaign.name %></td>
                <td><%= campaign.completion_status %></td>
                <td><%= link_to 'Show', campaign %></td>
                <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
                <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%#= button_to 'New Campaign', new_campaign_path %>
    </div>
  </div>

</div>

app/views/campaigns/new.html.erb
<div class="container">
  <div class="row">
    <div class="panel col-md-12 col-md-12">
      <h1>New Campaign</h1>
      <%= render 'form' %>
      <%= link_to 'Back', campaigns_path %>
    </div>
  </div>

</div>

app/views/campaigns/show.html.erb
<div class="container">
  <div class="row">
    <div class="panel col-md-12 col-md-12">
      <p>
        <strong>Campaign:</strong>
        <%= @campaign.name %>
      </p>

      <p>
        <strong>Client:</strong>
        <%= @campaign.client_name %>
      </p>

      <p>
        <strong>Completion Status:</strong>
        <%= @campaign.completion_status %>
      </p>

      <%= link_to 'Edit', edit_campaign_path(@campaign) %> |
      <%= link_to 'Back', campaigns_path %>
    </div>
  </div>

</div>