config/routes.rb
Rails.application.routes.draw do
  resources :recipient_lists
  mount RailsAdmin::Engine => 'admin', as: 'rails_admin'
  devise_for :users
  root to: "home#index"

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations'
  # }

  # resource :users, only: [:edit] do
  #   resource :profile, except: [:index], controller: 'users/profile' do
  #     member do
  #       put :update
  #     end
  #   end
  #   collection do
  #     put 'update_password'
  #   end
  # end
  resources :campaigns
  resources :emails

end

app/models/recipient_list.rb
class RecipientList < ActiveRecord::Base
  belongs_to :email
end

app/controllers/recipient_lists_controller.rb
class RecipientListsController < ApplicationController
  before_action :set_recipient_list, only: [:show, :edit, :update, :destroy]

  # GET /recipient_lists
  def index
    @recipient_lists = RecipientList.all
  end

  # GET /recipient_lists/1
  def show
  end

  # GET /recipient_lists/new
  def new
    @recipient_list = RecipientList.new
  end

  # GET /recipient_lists/1/edit
  def edit
  end

  # POST /recipient_lists
  def create
    @recipient_list = RecipientList.new(recipient_list_params)

    if @recipient_list.save
      redirect_to @recipient_list, notice: 'Recipient list was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /recipient_lists/1
  def update
    if @recipient_list.update(recipient_list_params)
      redirect_to @recipient_list, notice: 'Recipient list was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /recipient_lists/1
  def destroy
    @recipient_list.destroy
    redirect_to recipient_lists_url, notice: 'Recipient list was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipient_list
      @recipient_list = RecipientList.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recipient_list_params
      params.require(:recipient_list).permit(:name, :list, :references)
    end
end

app/views/recipient_lists/_form.html.erb
<%= simple_form_for(@recipient_list) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :list %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/recipient_lists/edit.html.erb
<div class="container">
  <div class="row">
    <div class="panel col-md-12 col-md-12">
      <h1 class="lead">Editing Recipient List: <span><%= @recipient_list.name %></span></h1>
      <%= render 'form' %>
      <%= link_to 'Back', recipient_lists_path %>
    </div>
  </div>

</div>

app/views/recipient_lists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-md-12">
      <h1 class="lead">Listing Recipient Lists</h1>
      <p><%= link_to 'New Recipient list', new_recipient_list_path, class: "button" %></p>

      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>List Name</th>
              <th>List</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @recipient_lists.each do |recipient_list| %>
              <tr>
                <td><%= recipient_list.name %></td>
                <td><%= recipient_list.list %></td>
                <td><%= link_to 'Show', recipient_list %></td>
                <td><%= link_to 'Edit', edit_recipient_list_path(recipient_list) %></td>
                <td><%= link_to 'Destroy', recipient_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>

</div>

app/views/recipient_lists/new.html.erb
<div class="container">
  <div class="row">
    <div class="panel col-md-12 col-md-12">
      <h1>New Recipient List</h1>
      <%= render 'form' %>
      <%= link_to 'Back', recipient_lists_path %>
    </div>
  </div>

</div>

app/views/recipient_lists/show.html.erb
<div class="container">
  <div class="row">
    <div class="panel col-md-12 col-md-12">
      <p>
        <strong>List Name:</strong>
        <%= @recipient_list.name %>
      </p>

      <p>
        <strong>Email Address List:</strong>
        <%= @recipient_list.list %>
      </p>

      <%= link_to 'Edit', edit_recipient_list_path(@recipient_list) %> |
      <%= link_to 'Back', recipient_lists_path %>
    </div>
  </div>

</div>